apiVersion: v1
kind: Service

metadata:
  name: springboot-demo-service
  namespace: jenkins

spec:

  selector:
    app: springboot-demo

  ports:

    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

  type: {{ .Values.service.type }}
