replicaCount: 2

image:
  repository: balu9963/springboot-demo
  tag: 1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  host: springboot.local

resources:
  requests:
    cpu: 250m
    memory: 512Mi

  limits:
    cpu: 500m
    memory: 1Gi
